### ISSUE TITLE
Automate the deployment

### ISSUE THREAD

**Issue by SketchNI** [MadhousePlatform/chatsharejs#5]
Currently, when a push is made to the `dev` branch (or a PR to the `main` branch), GitHub Actions picks up the changes and builds the docker image.

We then have to manually pull in the changes to the server and restart the docker container.
We should be able to automate this so all changes take effect *relatively* immediately

**Comment by PedroManuelAtienzaHuerta** [comment]
To automate the deployment to the server and restart the Docker container when a push to the `dev` branch or a pull request to the `main` branch is made, we can extend the Git workflow.

Here is an example of how you can modify your `chatshare.yml` workflow to include these steps:

1. **Connect to the server using SSH**: The `appleboy/ssh-action` action can be used to connect to the server.
2. **Deploy the new Docker image and restart the container**: Run commands on the server to update and restart the container.

```yaml
name: Build, Publish, and Deploy Docker Image for ChatShareJS

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/madhouseplatform/chatsharejs:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/madhouseplatform/chatsharejs:latest
            docker stop chatsharejs || true
            docker rm chatsharejs || true
            docker run -d --name chatsharejs -p 80:80 ghcr.io/madhouseplatform/chatsharejs:latest
```

This example assumes that you have the `SERVER_HOST`, `SERVER_USER`, and `SERVER_SSH_KEY` secrets configured in your GitHub repository. These secrets must contain the server host, the server name, and the server name.
